Update sync workflow to handle wierd diff stuff in Actions (#488)
Signed-off-by: Phil Dibowitz <phil@ipom.com>

diff --git a/.github/workflows/bot-daily-sync.yml b/.github/workflows/bot-daily-sync.yml
--- a/.github/workflows/bot-daily-sync.yml
+++ b/.github/workflows/bot-daily-sync.yml
@@ -2,24 +2,27 @@ name: Daily Upstream Sync
 
 on:
   workflow_dispatch:  # allow manual trigger from UI
+  pull_request:
+  push:
+    branches:
+      - main
   #schedule:
   #  - cron: '0 6 * * *'  # daily at 06:00 UTC, adjust as needed
 
 jobs:
   sync:
+    # Skip this job is a PR and comes from a fork (since it work work anyway)
+    if: github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository
     name: Run daily sync
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
-
-      - name: Add upstream remote
-        run: |
-          git remote add fb-upstream https://github.com/facebook/chef-cookbooks.git
-          git fetch fb-upstream
+          ref: refs/heads/main
+          persist-credentials: true
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -30,6 +33,24 @@ jobs:
         run: |
           python -m pip install --upgrade pip
 
+      - name: Configure git
+        run: |
+          git config --global core.autocrlf false
+          git config --global apply.whitespace nowarn
+          git config --global merge.renormalize true
+          git config --global user.name "GitHub Actions Bot"
+          git config --global user.email "noreply@github.com"
+          git remote add fb-upstream https://github.com/facebook/chef-cookbooks.git
+          git fetch fb-upstream
+
+      - name: Ensure branch setup is correct (for PRs only)
+        if: github.event_name == 'pull_request'
+        run: |
+          git fetch origin main
+          git checkout -B main origin/main || true
+          git reset --hard origin/main
+          git clean -fdx
+
       - name: Run sync bot
         env:
           UPSTREAM_REMOTE: fb-upstream
@@ -37,7 +58,11 @@ jobs:
           BASE_BRANCH: main
           TARGET_BRANCH: main
           PR_BRANCH_PREFIX: sync
+          GH_TOKEN: ${{ github.token }}
         run: |
-          git checkout ${{ env.TARGET_BRANCH }}
-          find .
+          # normalize line-endings or cherry-picking fails
+          git add --renormalize .
+          git stash push -k -m "temp normalization"
+
+          git diff --check
           ./scripts/fbchef_sync_bot.py
